[tool.poetry]
name = "test-engine-core-modules"
version = "0.9.0"
description = ""
authors = ["AI Verify"]
readme = "README.md"
packages = [{include = "test_engine_core_modules"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
joblib = "1.2.0"
libclang = "15.0.6.1"
numpy = "1.23.5"
scikit-learn = "1.2.2"
setuptools = "^67.7.2"
lightgbm = "3.3.5"
xgboost = "1.7.4"
tensorflow = "2.12.0"
pandas = "1.5.3"
scipy = "1.9.3"


[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.2"
black = "^23.3.0"
pytest = "^7.3.1"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
