name: Bug Report
description: File a bug/issue
title: "[BUG] <title>"
labels: ["bug-report", "needs-triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Description
    description: Provide a clear and concise description of the bug you encountered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: List the steps to reproduce the behavior. Be as specific as possible
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    value: |
        - Operating System and Version:
        - AI Verify Version:
        - Any other relevant information (e.g. version of related package dependencies installed):

        Did you build using source code or from docker file? If from source code, please provide the below information:
        - Python Version:
        - Node Version:
        - Redis Version:
        - Mongo Version: 
        - Screen Resolution:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots/ Code snippets
    description: |
      Include screenshots or code snippets that demonstrate the issue.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context
    description: Add any additional context about the problem here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Possible Solution (Optional)
    description: If you have any ideas or suggestions for a possible solution, you can include them here.
  validations:
    required: false
